name: vmf_lux_project
description: Proyecto VMF Lux
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.8.1
  image_picker: ^1.0.5
  intl: ^0.18.1
  url_launcher: ^6.1.14
  google_fonts: ^6.1.0

  # FIREBASE
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/vmf.png
    - assets/videos/
    - assets/images/
    # - assets/sounds/ 
