name: vmf_lux_project
description: Proyecto VMF Lux
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  video_player: ^2.8.1
  image_picker: ^1.0.5
  intl: ^0.18.1
  url_launcher: ^6.1.14
  google_fonts: ^6.1.0
  in_app_purchase: ^3.1.11
  
  # NavegaciÃ³n y Estado
  provider: ^6.1.1
  go_router: ^13.0.0
  
  # FIREBASE
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.4.10
  firebase_messaging: ^15.1.3
  firebase_dynamic_links: ^6.0.4
  
  # UI & Animaciones
  flutter_svg: ^2.0.9
  animations: ^2.0.8
  cached_network_image: ^3.3.0
  simple_animations: ^5.0.0
  
  # Multimedia & Audio
  youtube_player_flutter: ^9.1.3
  flutter_inappwebview: ^6.1.5
  audioplayers: ^6.1.0
  
  # Utils
  flutter_image_compress: ^2.0.4
  uuid: ^3.0.7
  shared_preferences: ^2.2.2
  purchases_flutter: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/vmf.png
    - assets/videos/
    - assets/images/
    # - assets/sounds/ 
